project:
  type: website
  output-dir: docs

website:
  title: "Haedodam Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fall-2025.qmd
        text: Fall 2025
    right:
      - icon: github
        href: "https://github.com/Haedodam"

format:
  html:
    theme: sandstone      
    mainfont: Arial
    monofont: "Courier New"
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"

resources:
  - resume.pdf
  - haedodam.jpg