project:
  type: website
  output-dir: docs

website:
  title: "Haedodam Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Resume
        href: resume.pdf
    right:
      - icon: github
        href: "https://github.com/Haedodam"
        
format:
  html:
    theme: minty
    mainfont: Arial
    fontsize: 1.5rem
    fontcolor: "#000000"

resources:
  - resume.pdf
  - haedodam.jpg